### ISSUE TITLE
Design new user registration

### ISSUE THREAD

**Issue by sukhbino** [cis350/agile-github-projects-team-team#5]

**Comment by paavneec** [comment]
User Flow Diagram: [https://drive.google.com/file/d/1VM7LHe6ooCYWrJCSt6cwSbnmRT6pFu3g/view?usp=sharing](url)
Wireframe + Prototype: [https://www.figma.com/file/5WH595Y6fQvUOhkcuVKVVf/CIS-350-Project-Wireframes-(TEAM-VERSION)?type=design&node-id=0%3A1&mode=design&t=QgdDOgjqwL0NhQHM-1](url)

**Comment by paavneec** [comment]
@tobinryan Can you close this issue now that it is done please

**Comment by paavneec** [comment]
@tobinryan can you assign this to me and put this in Milestone 1 just to ensure all issues are fully complete
